### ISSUE TITLE
Choose a Background / Scheduled job provider

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/vets-api#100]
(assuming we use ActiveJob in rails, backed by something else)
😄  = Resque
🎉  = Sidekiq
❤️  = DelayedJob
👎  = Other / Not ActiveJob

**Comment by robbiethegeek** [comment]
Can we generalize this, the implementation isn't defined yet

**Comment by markolson** [comment]
[ActiveJob](http://edgeguides.rubyonrails.org/active_job_basics.html) is a async runner framework included in Rails 4.2+ that generalizes the patterns usually found in things like Sidekiq or Resque. It seems like it's a safe bet to add and use as a front-end, and then we could drop into "raw" Sidekiq or Resque if we ever need the advanced features either of them offer.

**Comment by markolson** [comment]
[Sidekiq](http://sidekiq.org) is an open source async job system written in Ruby that has paid pro and enterprise options that offers support and other advanced options and tooling. I've personally used it and haven't had any issues with it. It, iirc, had some nice hooks for monitoring and alerting tools as well as solid retry mechanisms.

[Resque](https://github.com/resque/resque) is an open source job system written in Ruby that's .. really just about the same as Sidekiq. It's much more of a "pure" open source project, and so support tends to come from Stackoverflow and mailing lists, and it's been many many years since I've used it in production and so I can't speak to how it is to maintain and monitor.

Both Resque and Sidekiq are, to my eye, largely interchangeable, but I'd prefer Sidekiq a bit.
https://github.com/mperham/sidekiq/wiki/FAQ - some (perhaps biased) comparisons of sidekiq/resque/delayed_job
http://www.octolabs.com/blogs/octoblog/2013/12/13/background_smackdown_resque_vs_sidekiq/ - an older comparison
https://imvishaltyagi444.wordpress.com/2016/07/11/delayed-job-vs-resque-vs-sidekiq/ - more recent comparison

**Comment by lihanli** [comment]
for scheduling we can use cron or resque/sidekiq scheduler. i vote cron because it's the easiest option and i don't think we need any advanced features

**Comment by austin-martinez** [comment]
The main difference between Sidekiq and Resque is the use of threads vs. processes
https://github.com/mperham/sidekiq/wiki/FAQ

My preference would be for Sidekiq and whenever to create cron schedules
https://github.com/javan/whenever

**Comment by carlmjohnson** [comment]
I agree that for cron-like tasks, it would be better to do them in Ruby if possible. Cron is great and universally installed, but using it would mean that app developers would need to ask dev-ops developers any time a task schedule needs to be adjusted.

**Comment by lihanli** [comment]
we can add a deploy hook to have the whenever gem update the crontab after every deploy

**Comment by kreek** [comment]
I'll add my vote for Sidekiq because threads. I've used both Sidekiq and Resque, and if you end up with jobs that use multiple job instances (like batch processing) you are in for a world of race condition induced pain with processes. The one nice thing about Resque is it's scheduler extension, but I'm sure there's comparable extensions for Sidekiq. An extension is preferable IMO because schedules can be dynamic (15min from now) and also updated on the fly.

**Comment by saneshark** [comment]
@kreek fwiw sidekiq workers can be delayed in a similar manner as you describe, the delay and number of times to retry can be specified at the worker level or when the worker is invoked.

**Comment by robbiethegeek** [comment]
Going to close and @markolson is going to write up a design document for this feature.

**Comment by aub** [comment]
Apologies for reopening this, but I'm currently doing some work around task queueing and would like to revisit the use of ActiveJob. Having spoken with @markolson, @austin-martinez, and @saneshark about it, it seems no one is too thrilled with using it, and we should switch to using Sidekiq directly for the following reasons:

1. Because ActiveJob tries to be a wrapper around all job queueing systems, it implements the lowest common denominator of features for them. It is missing some features that we would like to use that are in the Sidekiq interface
1. In Rails 4, when queueing a job through ActiveJob there is no way to get the ID of the underlying Sidekiq job. This means that it would not be possible to allow watching the status of jobs that have been submitted via the API.
1. Because ActiveJob does not implement an interface for querying the status of jobs, we would need to access this information via the native Sidekiq interface anyway. So why not use it for job submissions as well.

I'm covering this issue along with other thing relevant to task queueing in a PR over here:

https://github.com/department-of-veterans-affairs/platform-team/pull/158
