### ISSUE TITLE
Create rake task for InProgressForms user_account backfill

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/vets-api#10207]
We need to backfill InProgressForms to have user_account_uuid, so create a rake task to do this, then we can run it to add user_account_uuid to all existing InProgressForm records

- [x] Create [process flow document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/documentation/Prod_db_change_process.md) for this and future requests of prod db changes being made with rake tasks
- [x] Request review of the process document by platform security
- [ ] Schedule rake task run
- [ ] Complete rake task and record all required documentation into this ticket

**Comment by joeniquette** [comment]
Doc PR: https://github.com/department-of-veterans-affairs/va.gov-team/pull/44416

going to ask for identity and security review

**Comment by joeniquette** [comment]
> Will Console Services Team be providing review or feedback given that this applies to `vets-api`?

Review of the process suggestion? Or review of the rake task itself? Im open to either if you think it would be helpful. The only requirement listed right now is that someone from operations would be required to review the rake task, perhaps this should be console services and not operations?

**Comment by joeniquette** [comment]
@mchelen-gov I made a new PR for the process doc: https://github.com/department-of-veterans-affairs/va.gov-team/pull/44616

**Comment by joeniquette** [comment]
Roll back plan
- something that deletes all `user_accounts` in `inprogressforms` table
- OR revert to snapshot of DB from before running script if above fail

Questions:
1. have we tested this script in a lower environment to validate it performs as expected
2. What could happen if the script doesnt do whats expected
3. How are we mitigating this? This can be, tested in lowers and validated that the script performs as expected plus test run a single account update in prod to verify there
4. If we detect this did not work as expected how can we revert it/backout plan

Answers:
1. I tested in localhost, but we should merge and test in staging. Would actually be a good test
2. The script wouldn’t negatively affect any records, if it didn’t do what we expect, there is no user information pollution. The user_uuid that we use to discover the UserAccount comes from the form itself, so the worst that can happen is we are unable to find a proper UserAccount to store on the form
3. I think running this on staging, then taking a random sampling of InProgressForms with user_account records added and confirming they are the ones we expect, would probably be sufficient
4. If this does not work as expected in a big way, we will set every record for the in_progress_forms.user_account_id to nil to mitigate

Additionally, the only line that actually updates the form is:
``` form.update!(user_account: user_account) ```
The `user_account` column isn’t actually used to query `InProgressForms` yet, so in a catastrophe for this specific column, there shouldn’t be any negative impact to current `InProgressForms`

Pointer to logs:
- In our case since we are not writing or updating PII we will not have a log per modification. Instead we will log the task write results. You can find the log here:
  - [Grafana Loki Search ](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%221658462400000%22,%221658548799000%22,%22Loki%20(Prod)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-server%5C%22,%20filename%3D~%5C%22.%2Bjson.log%5C%22%7D%5Cn%7C~%5C%22(%3Fi)%5BBackfillUserAccountIdForInProgressForms%5D%20InProgressForm%20with%20user_account_id:%20nil%5C%22%5Cn%7C%20regexp%20%5C%22(%3FP%3Ctime%3E%5C%5C%5C%5Cd%5C%5C%5C%5Cd:%5C%5C%5C%5Cd%5C%5C%5C%5Cd:%5C%5C%5C%5Cd%5C%5C%5C%5Cd)%20(%3FP%3Cprocess_name%3E%5C%5C%5C%5Cw%2B.%5C%5C%5C%5Cd)%20%5C%5C%5C%5Cs%2B%20(%5C%5C%5C%5C%7C)%20(%3FP%3Cjson%3E.%2B)%5C%22%20%5Cn%7C%20line_format%20%5C%22%7B%7B.json%7D%7D%20%5C%22%23Remote_IP%20%3D%20%7B%7B.named_tags_remote_ip%7D%7D%5C%5Ct%5C%22%5Cn%7C%20json%22,%22maxLines%22:5000,%22datasource%22:%22Loki%20(Dev)%22%7D%5D) (need to modify date to see log)

Produce test results from localhost and staging:
- Localhost:
 ``` 
 2022-07-21 10:06:45.664297 I [46862:69800] Rails -- [BackfillUserAccountIdForInProgressForms] Starting rake task
2022-07-21 10:06:45.728155 D [46862:69800] ActiveRecord::Base --    (0.4ms)  SELECT COUNT(*) FROM “in_progress_forms” WHERE “in_progress_forms”.“user_account_id” IS NULL
2022-07-21 10:06:45.728453 I [46862:69800] Rails -- [BackfillUserAccountIdForInProgressForms] InProgressForm with user_account_id: nil, count: 0
2022-07-21 10:06:45.730406 D [46862:69800] ActiveRecord::Base --   InProgressForm Load (0.1ms)  SELECT “in_progress_forms”.* FROM “in_progress_forms” WHERE “in_progress_forms”.“user_account_id” IS NULL ORDER BY “in_progress_forms”.“id” ASC LIMIT $1  [[“LIMIT”, 1000]]
2022-07-21 10:06:45.730783 I [46862:69800] Rails -- [BackfillUserAccountIdForInProgressForms] Finished rake task
2022-07-21 10:06:45.731058 D [46862:69800] ActiveRecord::Base --    (0.1ms)  SELECT COUNT(*) FROM “in_progress_forms” WHERE “in_progress_forms”.“user_account_id” IS NULL
2022-07-21 10:06:45.731243 I [46862:69800] Rails -- [BackfillUserAccountIdForInProgressForms] InProgressForm with user_account_id: nil, count: 0 
```
- Staging:
```

**Comment by ianhundere** [comment]
successfully ran task in production:
```
{"host":"064519c459a7","application":"vets-api-server","environment":"production","timestamp":"2022-07-29T00:33:27.101541Z","level":"info","level_index":2,"pid":6243,"thread":"67860","name":"Rails","message":"[BackfillUserAccountIdForInProgressForms] Starting rake task"}
{"host":"064519c459a7","application":"vets-api-server","environment":"production","timestamp":"2022-07-29T00:33:27.157317Z","level":"info","level_index":2,"pid":6243,"thread":"67860","name":"Rails","message":"[BackfillUserAccountIdForInProgressForms] InProgressForm with user_account_id: nil, count: 62557"}
{"host":"064519c459a7","application":"vets-api-server","environment":"production","timestamp":"2022-07-29T00:48:28.353386Z","level":"info","level_index":2,"pid":6243,"thread":"67860","name":"Rails","message":"[BackfillUserAccountIdForInProgressForms] Finished rake task"}
{"host":"064519c459a7","application":"vets-api-server","environment":"production","timestamp":"2022-07-29T00:48:28.383441Z","level":"info","level_index":2,"pid":6243,"thread":"67860","name":"Rails","message":"[BackfillUserAccountIdForInProgressForms] InProgressForm with user_account_id: nil, count: 47954"}
I, [2022-07-29T00:48:29.592570 #6243]  INFO -- ddtrace: [ddtrace] DATADOG TRACER CONFIGURATION - {"date":"2022-07-29T00:48:29+00:00","os_name":"x86_64-pc-linux-gnu","version":"0.54.2","lang":"ruby","lang_version":"2.7.6","env":"production","enabled":true,"service":"vets-api","agent_url":"http://datadog-agent:8126?timeout=30","debug":false,"analytics_enabled":false,"runtime_metrics_enabled":false,"integrations_loaded":"rake@13.0.6,sidekiq@6.4.1,rails@6.1.6.1,rack@2.2.4,action_mailer@6.1.6.1,active_support@6.1.6.1,action_pack@6.1.6.1,action_view@6.1.6.1,active_job@6.1.6.1,active_record@6.1.6.1","vm":"ruby-2.7.6","partial_flushing_enabled":false,"priority_sampling_enabled":false,"health_metrics_enabled":false,"integration_rake_analytics_enabled":"false","integration_rake_analytics_sample_rate":"1.0","integration_rake_enabled":"true","integration_rake_service_name":"rake","integration_rake_quantize":"{}","integration_sidekiq_analytics_enabled":"false","integration_sidekiq_analytics_sample_rate":"1.0","integration_sidekiq_enabled":"true","integration_sidekiq_service_name":"sidekiq","integration_sidekiq_tag_args":"false","integration_sidekiq_client_service_name":"sidekiq-client","integration_sidekiq_error_handler":"#<Proc:0x00005566d75311d0 /usr/local/bundle/gems/ddtrace-0.54.2/lib/ddtrace/tracer.rb:33>","integration_rails_analytics_enabled":"","integration_rails_analytics_sample_rate":"1.0","integration_rails_enabled":"true","integration_rails_service_name":"vets-api","integration_rails_cache_service":"vets-api-cache","integration_rails_controller_service":"vets-api","integration_rails_database_service":"vets-api-postgis","integration_rails_distributed_tracing":"true","integration_rails_exception_controller":"","integration_rails_job_service":"vets-api-active_job","integration_rails_middleware":"true","integration_rails_middleware_names":"false","integration_rails_template_base_path":"views/","integration_rails_log_injection":"false","integration_rack_analytics_enabled":"","integration_rack_analytics_sample_rate":"1.0","integration_rack_enabled":"true","integration_rack_service_name":"vets-api","integration_rack_application":"#<VetsAPI::Application:0x00005566dfedaf58>","integration_rack_distributed_tracing":"true","integration_rack_headers":"{:response=>[\"Content-Type\", \"X-Request-ID\"]}","integration_rack_middleware_names":"false","integration_rack_quantize":"{}","integration_rack_request_queuing":"false","integration_rack_web_service_name":"web-server","integration_action_mailer_analytics_enabled":"false","integration_action_mailer_analytics_sample_rate":"1.0","integration_action_mailer_enabled":"true","integration_action_mailer_service_name":"vets-api-action_mailer","integration_action_mailer_email_data":"false","integration_active_support_analytics_enabled":"false","integration_active_support_analytics_sample_rate":"1.0","integration_active_support_enabled":"true","integration_active_support_service_name":"","integration_active_support_cache_service":"vets-api-cache","integration_action_pack_analytics_enabled":"","integration_action_pack_analytics_sample_rate":"1.0","integration_action_pack_enabled":"true","integration_action_pack_service_name":"vets-api","integration_action_pack_controller_service":"vets-api","integration_action_pack_exception_controller":"","integration_action_view_analytics_enabled":"false","integration_action_view_analytics_sample_rate":"1.0","integration_action_view_enabled":"true","integration_action_view_service_name":"vets-api","integration_action_view_template_base_path":"views/","integration_active_job_analytics_enabled":"false","integration_active_job_analytics_sample_rate":"1.0","integration_active_job_enabled":"true","integration_active_job_service_name":"vets-api-active_job","integration_active_job_error_handler":"#<Proc:0x00005566d75311d0 /usr/local/bundle/gems/ddtrace-0.54.2/lib/ddtrace/tracer.rb:33>","integration_active_job_log_injection":"false","integration_active_record_analytics_enabled":"false","integration_active_record_analytics_sample_rate":"1.0","integration_active_record_enabled":"true","integration_active_record_service_name":"vets-api-postgis","integration_active_record_orm_service_name":""}
```
