### ISSUE TITLE
Make SAML errors conform to JSON-API spec

### ISSUE THREAD

**Issue by shauni** [department-of-veterans-affairs/vets-api#191]
https://github.com/department-of-veterans-affairs/vets-api/pull/184#discussion_r81215842

**Comment by saneshark** [comment]
@omgitsbillryan this appears to have the veterans-day tag, please assign to me if you don't have the bandwidth before 11/11 and I'm happy to take a look.

**Comment by omgitsbillryan** [comment]
You're right, re-assining to you.

**Comment by saneshark** [comment]
I looked through the code in sessions_controller and with the way we're currently doing redirects, this PR can just be closed.

It's still unclear to me what would happen in the event that something goes wrong, raising an exception. For example, lets say a 500 error is raised while trying to persist the session to redis, this would go through the application_controller, and return JSON with a 500 http status code. Does ID.me then handle that error somehow? I want to make sure that we're at least doing somewhat strong negative testing with respect to these types of scenarios that could arise since the user's flow is in the hands of ID.me when an error occurs in saml_callback, it's not in the hands of our F/E.

To help facillitate this discovery I think it will be important to have some automated testing, perhaps creating a mock saml idp helper and writing a few rspec tests to make sure we've gone through the entire flow for these callbacks and ensured everything is working fine from our perspective. Doing some manual QA to see what the rendered response is from ID.me in the negative tests will be valuable insight to have as well.

I am going to go ahead and close this issue and open a separate one without the veterans-day label in which we can track improving specs.

**Comment by saneshark** [comment]
@omgitsbillryan and @aub I've had side-bar conversations with you both. Please feel free to re-open this issue if you think it's necessary. I'll open a separate thread about improving specs as discussed above.
