### ISSUE TITLE
Add pessimistic gem versioning to Gemfile

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/vets-api#207]
Many of the gem definitions don't have constraints (version numbers). Add pessimistic constraints (e.g. `'my_gem', '~> 1.1'`) so running bundle update (or bundle on a fresh checkout) doesn't move any gems to a version that our code doesn't support.

**Comment by saneshark** [comment]
@kreek I think you should be able to run `bundle` or `bundle install` without ever doing `bundle update` If you ever need to bump versions of a specific library then `bundle update <some_gem>`

**Comment by kreek** [comment]
ok, I still think it's good practice to include the version you want to be at, and pessimistic allows you to get micro version bug fixes

**Comment by robbiethegeek** [comment]
I think that being as defensive as possible here is a good thing.  In node there is the Node Security Project that will release a new advisory and we can add it to the linting process.  Is there something similair in the Ruby ecosystem or do we need to have a weekly task to check out gems?

**Comment by ayaleloehr** [comment]
We have [bundler-audit](https://github.com/rubysec/bundler-audit) in our [Gemfile](https://github.com/department-of-veterans-affairs/vets-api/blob/master/Gemfile#L52), which I think is what you're referring to @robbiethegeek   

I am on board with having `'~> version.number'` for each gem.

**Comment by saneshark** [comment]
Adding pessimistic version constraints to certain critical gems makes a lot of sense. Adding it to all gems less so.

To avoid further bike-shedding I'll just paste a link here that discusses the benefits and drawbacks. Since we check our Gemfile.lock into source control and we do Code Reviews, and particularly because we are still very much in active development, I think it might just slow development down to add these types of constraints for anything non critical.

https://robots.thoughtbot.com/a-healthy-bundle

**Comment by saneshark** [comment]
Here is an example of how it gets confusing to introduce these types of constaints. 

Say I want to install carrierwave. I look at the README for master and I see the following recommendation:

> This README is for a branch which is still in development. Please switch to latest 0.x branch for stable version.

further down it says the recommended way of including it in rails is:

```ruby
gem 'carrierwave', '>= 1.0.0.beta', '< 2.0'
```

This would be an example of an optimistic constraint and problematic for us to introduce. I'm all for having a pessimistic constraint on a gem such as this, but I notice that their stable branch v0.11 tagged branch says to just do:

```
gem 'carrierwave'
```

So I go with that and I do a bundle install. But I notice it doesn't install 0.11 as I expected, because some pessimistic constraint we put on a dependency is forcing it to install a different version than the desired and expected version. Or maybe I don't realize this and proceed to follow the documentation for 0.11 and assume I must be doing something wrong because some feature is not yet available.

Whereas instead if we had just followed the recommendation for most of the gems that are dependencies and only set constraints when we ran into problems that we were unable to address, this would have never been an issue and gems would organically update as new gems are introduced. If a particular gem gets updated that raises eyebrows we should identify it in code review. Certain gems like Rails and ActiveRecord should definitely be locked down. But all gems?

We already have protection against production deviating from development environments, thats the whole point of the Gemfile.lock. By putting constraints we don't let bundler do its job. In fact, I think we should be actively, perhaps even weekly bumping versions of gems to the latest stable versions while we are in active development. We should be deligent in researching any new dependencies that are added during code review. Otherwise we end up having a situation 4-6 months down the line where there is a huge tech debt and countless specs that are failing.

Anyway, that's my $0.02. Highly recommend reading the last two paragraphs of that link I provided in the previous comment.

**Comment by kreek** [comment]
I'm fine with the version being for a set of core gems, rails-api, pg, etc.

**Comment by ayaleloehr** [comment]
Making a call that ^ is a good enough decision.  Assigning to @kreek

**Comment by robbiethegeek** [comment]
@ayaleloehr ++ this comment made me LOL for realz!  

LGTM also :shipit:

**Comment by robbiethegeek** [comment]
@omgitsbillryan @aub @kreek  this is done or completely stalled correct?

**Comment by omgitsbillryan** [comment]
Stalled completed from my perspective.

**Comment by aub** [comment]
We've talked about this a lot, both here and in a PR generated from this issue. There are a number of different approaches, and while they all have some merit I'm partial to the one that works perfectly well while requiring the least work and the least maintenance. If we go without versions in the Gemfile then we incur very little risk because the gems are locked and because code review would presumably catch any rogue gem upgrading. Doing so requires no work up front and is the easiest to maintain because we don't have to manually update versions in the Gemfile for each upgrade. I'd propose that we only specify versions there when there is a specific reason to believe that only the given version will work or that we want to specifically forbid upgrades. Those locks should include a comment in the Gemfile to indicate why the lock was added. And I'm closing this ticket because I believe this is very close to where we already are today.
