### ISSUE TITLE
Improve Test Coverage around SessionsController

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/vets-api#480]
This will be tricky since we'll need to build a Mock SAML IDP, but I think there is probably a ruby project somewhere that allows you to run your own IDP and we can hijack whatever helpers it uses or build from scratch if necessary.

The idea would be to have both negative and positive tests recorded and as close to 100% test coverage for sessions_controller that we can manage to get. It might be difficult to do this as request specs, but even controller specs would be better than nothing at all. 

BONUS: In addition we should investigate having a separate CI that does cucumber style specs with both vets-website and vets-api using pre-recorded vcr cassettes for both negative and positive testing of ID.me sign-in, loa leveling up, sign-out, etc.

**Comment by greggersh** [comment]
I have a few SAML IDPs that can be used for testing/mocking.

**Comment by omgitsbillryan** [comment]
@saneshark I _don't_ like the idea of running our own separate IDP since it creates an external dependency on unit tests that should be able to run in a vacuum.  I _do_ like the idea of using `VCR` since right now we have some clumsy method stubs that are basically trying to mock out API requests.  The only challenge I foresee is the fact that we use a different SP cert for each environment; `dev`, `staging`, & `prod`.

As for the separate CI cucumber style specs, I think that the amount of work is not worth the reward.  VCR style controller specs are nearly as good for a fraction of the work.

FWIW, as of today, our sessions_controller coverage sits at ~94% (granted there's some `:nocov:` around SAML SLO).

**Comment by omgitsbillryan** [comment]
@saneshark also, welcome to over a month later :smile: , care to update anything?

**Comment by saneshark** [comment]
So it was specifically around the SAML SLO that I thought it might be worth while to have some coverage, but seems like we've gone without issue on that for quite some time now. I won't make the call to close this issue though since I'm not on core really anymore. Feel free to close if you want @omgitsbillryan

**Comment by ayaleloehr** [comment]
@saneshark @omgitsbillryan should this be closed?  or moved to vets.gov-team and labeled properly?
